# File: .github/workflows/repo-sync.yml 借用了JD_BASH的代码
name: A自动同步A
on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: repo-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 同步到gitee使用，需要在github的secrets里添加GITEE_PRIVATE_KEY，填写gitee公钥
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 开始自动同步
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/garypang13/OpenWrt.git" #源地址
          source_branch: "master" #此处双方分支必须填对
          destination_branch: "main"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      # 同步到gitee使用
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master #使用Yikun的代码，不用修改
        if: env.dst_key
        with:
          src: github/lansi1d #源名称
          dst: gitee/lansild #目标名称
          static_list: "autojd" #同步的项目
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }} #同步到gitee使用，需要在github的secrets里添加GITEE_TOKEN
